### ISSUE TITLE
Google+ Oauth issue 

### ISSUE THREAD

**Issue by bewithsahilsaif** [homakov/oauthsecurity#7]
Hi @homakov  @isciurus  and @0xdabbad00 ,

I want to contribute to oauthsecurity.com. Actually there is an issue with  Google Plus Oauth.  Without wasting you time. Let me explain you issue. 
1. Open up an application, which uses Google plus for signup
2. Clicking on Sign up with Google + 
   
   /connect/provider
3. After approving request

provider.com/oauth/authorize?client_id=CLIENT_ID&redirect_uri=CLIENT//?token=<system_generated_token>&email=<email_address>&state=STATE TOKEN

Then, Application redirects us to

CLIENT /?token=<system_generated_token>&email=<email_address>&state=STATE TOKEN

Now, To take over someone else account just intercept the above request and change the email parameter to victims email

CLIENT /?token=<system_generated_token>&email=<victim_email_address>&state=STATE TOKEN

After forwarding the request attacker will be logged into Victims account. This issue occur due to the poor configuration of Google+ Oauth application.

I have tested 5 web applications, which uses Google plus Oauth and 3 of them is vulnerable to Account takeover bug.

Let me know if you need to know anything about this issue. 

Thanks 
@bewithsahilsaif

**Comment by prakharprasad** [comment]
Why don't you fork the project, add your write-up (in a good format) and send a PR ?
